#!/bin/sh
log=~/.CustomLogin/gnome-settings-daemon-killer.log

echo "started: `date`" > $log

# wait for it to start up
while [ "x`pidof gnome-settings-daemon`" = "x" ]
do
    sleep 1
done

# make sure it's done starting
sleep 1

# kill & restart to re-apply keyboard shortcuts
killall gnome-settings-daemon >> $log

echo "done: `date`" >> $log

